import type { Locale } from "./content/pages.ts";
import { arrow, contactPath, path, picture, t } from "./lib.ts";
import { contactCallout, faq, zones } from "./components.ts";
import { hospitalityArt } from "./art.ts";
import { reviews } from "./reviews.ts";
import { managementArt } from "./management-art.ts";
import { pricing } from "./pricing.ts";
import { intendanceSlug } from "./content/intendance.ts";

export function home(locale: Locale): string {
  const questions = [
    {
      question: t(locale, "Puis-je continuer à profiter de ma maison ?", "Can I still enjoy my own home?"),
      answer: t(locale, "Oui. Vous choisissez vos périodes d’occupation et nous les bloquons dans le calendrier, en tenant compte des réservations déjà confirmées. Le coût de préparation pour vos séjours est précisé dans votre proposition.", "Yes. You choose your own stays and we block them in the calendar, taking confirmed bookings into account. The preparation cost for your own stays is specified in your proposal."),
    },
    {
      question: t(locale, "Comment serai-je informé de ce qui se passe dans ma maison ?", "How will I know what is happening in my home?"),
      answer: t(locale, "Vous échangez directement avec notre équipe. Nous vous signalons les anomalies et les interventions qui nécessitent votre décision. Une facture mensuelle détaille nos honoraires et les prestations facturées.", "You speak directly with our team. We flag issues and work that needs your decision. A monthly invoice details our fees and any services charged."),
    },
    {
      question: t(locale, "Que se passe-t-il en cas de problème pendant un séjour ?", "What happens if there is a problem during a stay?"),
      answer: t(locale, "Notre assistance voyageurs est disponible 24 h/24, 7 j/7. Nous répondons, évaluons le problème et organisons sa résolution avec les intervenants nécessaires. Le délai d’intervention sur place dépend de la situation et de la disponibilité des prestataires. Nous vous tenons informé et vous soumettons les achats ou réparations supplémentaires à votre charge.", "Our guest assistance is available 24/7. We respond, assess the issue and arrange its resolution with the people needed. The time for an on-site visit depends on the situation and contractor availability. We keep you informed and ask you to approve extra purchases or repairs at your expense."),
    },
    {
      question: t(locale, "Et si des dommages sont constatés ?", "What happens if damage is found?"),
      answer: t(locale, "Nous suivons les démarches et les justificatifs nécessaires auprès des interlocuteurs concernés. Une indemnisation dépend des conditions de la plateforme, du dépôt de garantie ou de l’assurance applicable ; elle n’est pas automatique.", "We follow up the procedures and supporting documents with the relevant parties. Compensation depends on the platform, deposit or insurance terms that apply; it is not automatic."),
    },
    {
      question: t(locale, "Pouvez-vous reprendre une location déjà en cours ?", "Can you take over an existing rental?"),
      answer: t(locale, "Oui. Avant la reprise, nous examinons l’annonce, les réservations déjà confirmées et les accès nécessaires aux comptes et au logement. Nous précisons ensuite la date de démarrage et l’organisation de la transition. Le transfert des comptes, des avis ou des réservations n’est pas automatique.", "Yes. Before taking over, we review your listing, confirmed bookings and the access needed to accounts and the property. We then agree the start date and transition arrangements. Accounts, reviews and bookings do not transfer automatically."),
    },
    {
      question: t(locale, "Quelle est la durée de l’engagement et comment se termine la prestation ?", "How long is the agreement and how does management end?"),
      answer: t(locale, "La durée est précisée dans votre contrat. Les CGV prévoient une reconduction tacite et un préavis de deux mois avant l’échéance, par lettre recommandée avec accusé de réception. À la fin de la prestation, les réservations déjà confirmées sont honorées jusqu’à leur terme et les commissions correspondantes restent dues.", "The term is specified in your agreement. The terms provide for automatic renewal and two months’ notice before the end date, by registered letter with acknowledgement of receipt. Confirmed bookings are honoured through completion and the corresponding commissions remain payable."),
    },
    {
      question: t(locale, "Puis-je vous confier seulement le ménage ou l’annonce ?", "Can I book cleaning or listing management on its own?"),
      answer: t(locale, "Pour vos locations, l’annonce, les échanges voyageurs et les rotations font partie de la gestion complète. Pour une résidence secondaire à usage personnel, notre offre d’intendance prévoit des visites régulières et des prestations complémentaires sur devis. Nous ne proposons pas de ménage ou de gestion d’annonce isolés en dehors de ces offres.", "For rentals, listings, guest communication and changeovers are part of full management. For a second home used for your own stays, our home-care service provides regular visits and separately quoted extras. We do not provide standalone cleaning or listing management outside these services."),
    },
  ];
  const properties = [
    { image: "villa_amichi", name: "Villa d’Amichi", location: "Pinarello · Zonza", type: t(locale, "Villa", "Villa") },
    { image: "casa_verde", name: "Casa Verde", location: "Pinarello · Zonza", type: t(locale, "Maison", "House") },
    { image: "villa_lova", name: "Cala Lova", location: "Cala d’Oro · Solenzara", type: t(locale, "Maison de caractère", "Character home") },
  ];
  const steps = [
    [t(locale, "Présentez-nous votre maison.", "Tell us about your home."), t(locale, "Où se trouve votre bien ? Est-il déjà loué ? Quand souhaitez-vous déléguer sa gestion ? Quelques informations suffisent pour ouvrir la discussion.", "Where is your home? Is it already rented out? When would you like us to take over? A few details are enough to start the conversation.")],
    [t(locale, "Vérifions la prise en charge.", "Check whether we can manage it."), t(locale, "Nous échangeons sur le logement, ses accès et l’organisation à prévoir pour vérifier les possibilités de prise en charge.", "We discuss the property, its access and the arrangements needed to check whether we can manage it.")],
    [t(locale, "Examinez votre proposition.", "Review your proposal."), t(locale, "Si la prise en charge est possible, les prestations, honoraires, frais distincts et conditions sont précisés avant le démarrage.", "If we can take on your home, services, management fees, separate costs and terms are set out before work begins.")],
  ];
  return `
  <section class="home-hero">
    <div class="hero-aura" aria-hidden="true"></div>
    <div class="hero-topline container"><p class="eyebrow"><span class="status-dot" aria-hidden="true"></span>${t(locale, "CONCIERGERIE FAMILIALE · DE GHISONACCIA À PORTO-VECCHIO", "A FAMILY TEAM · FROM GHISONACCIA TO PORTO-VECCHIO")}</p><span class="hero-coordinate" aria-hidden="true">42° N · 09° E</span></div>
    <div class="hero-main container">
      <div class="hero-copy"><h1><span>${t(locale, "Déléguez votre location en Corse.", "Hand over your Corsican rental.")}</span><span class="hero-accent">${t(locale, "Gardez la main sur votre maison.", "Keep control of your home.")}</span></h1>
      <p class="hero-description">${t(locale, "Notre équipe familiale organise les réservations, les séjours et le suivi du logement. Vous conservez vos périodes personnelles et les décisions sur les dépenses supplémentaires.", "Our family team organises bookings, stays and care for your property. You keep your own stays and decide on additional expenses.")}</p>
      <p class="hero-assistance">${t(locale, "Assistance voyageurs 24 h/24, 7 j/7", "Guest assistance available 24/7")}</p>
      <p class="hero-location">${t(locale, "Votre conciergerie familiale, de Ghisonaccia à Porto-Vecchio.", "Your family-run property management team, from Ghisonaccia to Porto-Vecchio.")}</p>
      <div class="hero-actions"><a class="button" href="${contactPath(locale, "gestion")}">${t(locale, "Demander ma proposition de gestion", "Request my management proposal")}${arrow}</a><a class="text-link" href="${path(locale, "audit-gratuit-potentiel-locatif")}">${t(locale, "Encore en réflexion ? Découvrez l’audit gratuit", "Still considering it? Explore the free review")}${arrow}</a></div>
      <p class="hero-reassurance">${t(locale, "Votre adresse et vos accès sont vérifiés avant confirmation de la prise en charge. Vous examinez les conditions avant de décider.", "We check your address and access before confirming management. You review the terms before deciding.")}</p><p class="hero-reassurance hero-fees">${t(locale, "20 % TTC des nuitées, avant frais de plateforme. Hors ménage, linge et taxe de séjour.", "20% incl. VAT of accommodation charges, before platform fees. Excluding cleaning, linen and tourist tax.")} <a href="#tarifs">${t(locale, "Comprendre les honoraires", "Understand our fees")}</a></p></div>
      <div class="hero-visual" data-hospitality-scene data-illustration-active="false" aria-hidden="true">${hospitalityArt(locale)}</div>
    </div>
    <div class="hero-bottom container"><a class="scroll-cue" href="#services"><span aria-hidden="true">↓</span>${t(locale, "Votre gestion, en un regard", "Your management, at a glance")}</a><p class="territory-note">${t(locale, "De Ghisonaccia à Porto-Vecchio", "From Ghisonaccia to Porto-Vecchio")}</p><button id="motion-toggle" type="button" aria-pressed="false" aria-label="${t(locale, "Mettre les animations en pause", "Pause animations")}" data-pause="${t(locale, "Mettre les animations en pause", "Pause animations")}" data-play="${t(locale, "Reprendre les animations", "Resume animations")}"><span class="motion-icon" aria-hidden="true">Ⅱ</span><span class="motion-label">${t(locale, "Animations", "Animations")}</span></button></div>
  </section>
  <div class="services-section" id="services"><span id="formules" class="anchor-target" aria-hidden="true"></span><span id="comparaison" class="anchor-target" aria-hidden="true"></span>
    ${managementArt(locale)}
    <div class="container home-service-summary"><p>${t(locale, "Vous choisissez vos séjours personnels et validez les dépenses supplémentaires. Nous vous tenons informé du suivi de votre maison.", "You choose your own stays and approve extra expenses. We keep you informed about the care of your home.")}</p><a class="text-link" href="${path(locale, "gestion-airbnb-corse-du-sud")}#section-1">${t(locale, "Voir les sept prestations en détail", "Explore all seven services")}${arrow}</a></div>
  </div>
  <section class="presence-section" id="equipe"><div class="container">
    <div class="presence-grid"><div class="presence-heading" data-reveal><p class="eyebrow">${t(locale, "UNE ÉQUIPE FAMILIALE", "A FAMILY TEAM")}</p><h2>${t(locale, "Une équipe à Travo,<br><em>un lien direct avec votre maison.</em>", "A team in Travo,<br><em>a direct connection to your home.</em>")}</h2></div><div class="presence-copy" data-reveal><p class="presence-lead">${t(locale, "Une équipe familiale, un lien direct pour votre maison.", "A family team based in Travo, a direct connection to your home.")}</p><p>${t(locale, "Nous sommes nous-mêmes propriétaires. Nous savons que déléguer une location ne revient pas seulement à remplir un calendrier : il faut aussi savoir à qui parler et quelles décisions prendre. Vous échangez directement avec notre équipe. Les besoins d’intervention et les dépenses supplémentaires vous sont présentés pour décision.", "As homeowners ourselves, we know that handing over a rental is about more than filling a calendar: you need to know who to speak to and which decisions to make. You deal directly with our team. We bring work that is needed and additional expenses to you for a decision.")}</p><div class="home-care-proof"><h3>${t(locale, "Le soin du logement passe par des vérifications.", "Caring for a home means checking it.")}</h3><p>${t(locale, "La préparation entre les séjours s’appuie sur une checklist et des photos de fin d’intervention. Les anomalies constatées sont signalées et les suites nécessaires sont organisées.", "Preparation between stays uses a checklist and photos at the end of the work. Any issues found are reported and the necessary follow-up is organised.")}</p></div><a class="text-link" href="${path(locale, "about")}">${t(locale, "Découvrir notre façon de travailler", "Discover how we work")}${arrow}</a></div></div>
    <div class="local-area" id="zone"><div><h3>${t(locale, "La côte orientale, au quotidien.", "Corsica’s east coast, every day.")}</h3><p>${t(locale, "De Ghisonaccia à Porto-Vecchio, en passant par Ventiseri, Solenzara, Sainte-Lucie de Porto-Vecchio et Lecci. Votre adresse permet de confirmer les prestations possibles.", "From Ghisonaccia to Porto-Vecchio, through Ventiseri, Solenzara, Sainte-Lucie de Porto-Vecchio and Lecci. Your address lets us confirm the services available.")}</p></div><div class="zone-list">${zones.map(([name, slug]) => `<a href="${path(locale, slug)}"><span>${name}</span>${arrow}</a>`).join("")}</div></div>
  </div></section>
  <section class="section portfolio-section" id="portfolio"><span id="resultats" class="anchor-target" aria-hidden="true"></span><div class="container">
    <div class="section-heading" data-reveal><div><p class="eyebrow">${t(locale, "LES MAISONS ET LES SÉJOURS", "HOMES AND STAYS")}</p><h2>${t(locale, "Des maisons accompagnées<br><em>sur notre secteur.</em>", "Homes we look after<br><em>across our area.</em>")}</h2></div><p>${t(locale, "Quelques maisons de notre portfolio, sur la côte orientale. Leur configuration, leurs accès et les habitudes de leurs propriétaires guident l’organisation de notre gestion.", "A few homes from our east coast portfolio. Their layout, access and owners’ routines shape how we organise management.")}</p></div>
    <div class="property-list">${properties.map((property, index) => `<figure class="property-row" data-reveal><span class="property-index">0${index + 1}</span>${picture(property.image, `${property.name} · ${property.location}`, "property-thumb")}<figcaption><span class="eyebrow">${property.type}</span><h3>${property.name}</h3><p>${property.location}</p></figcaption></figure>`).join("")}</div>
    ${reviews(locale)}
  </div></section>
  ${pricing(locale, false)}
  <section class="section process-section" id="processus"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">${t(locale, "DU PREMIER ÉCHANGE AU DÉMARRAGE", "FROM FIRST CONTACT TO GETTING STARTED")}</p><h2>${t(locale, "Présenter votre bien<br><em>ne vous oblige pas à décider tout de suite.</em>", "Tell us about your home.<br><em>You don’t have to decide straight away.</em>")}</h2></div></div><ol class="process-list">${steps.map(([title, text], index) => `<li data-reveal><span class="step-index">0${index + 1}</span><div><h3>${title}</h3><p>${text}</p></div></li>`).join("")}</ol><p class="process-note">${t(locale, "Les prestations, le coût et les modalités de la gestion sont précisés avant de commencer.", "Services, costs and management arrangements are specified before work begins.")} <a href="/cgv" lang="fr">${t(locale, "Consulter les CGV", "Read the terms (French)")}</a>.</p></div></section>
  <section class="section home-other-needs"><div class="container home-other-needs-grid"><article><p class="eyebrow">${t(locale, "AUDIT GRATUIT", "FREE PROPERTY REVIEW")}</p><h2>${t(locale, "Vous avez encore besoin de faire le point ?", "Still need to review your plans?")}</h2><p>${t(locale, "L’audit gratuit sert à identifier les priorités et les informations à réunir avant une éventuelle délégation. Il s’agit d’une analyse qualitative, pas d’une estimation de revenus.", "The free review helps identify priorities and the information needed before a possible handover. It is a qualitative review, not an income estimate.")}</p><a class="text-link" href="${path(locale, "audit-gratuit-potentiel-locatif")}">${t(locale, "Découvrir ce que comprend l’audit", "Explore what the review includes")}${arrow}</a></article><article><p class="eyebrow">${t(locale, "INTENDANCE", "SECOND-HOME CARE")}</p><h2>${t(locale, "Vous cherchez surtout un suivi pendant vos absences ?", "Looking for care while you are away?")}</h2><p>${t(locale, "Pour les visites de votre résidence secondaire et les prestations liées à vos propres séjours, découvrez l’intendance. Cette offre ne comprend pas l’organisation des locations ni l’assistance aux voyageurs.", "Explore home care for visits to your second home and services for your own stays. This service does not include managing rentals or assisting guests.")}</p><a class="text-link" href="${path(locale, intendanceSlug)}">${t(locale, "Voir l’intendance et ses tarifs", "Explore home care and its prices")}${arrow}</a></article></div></section>
  ${faq(locale, questions)}${contactCallout(locale)}`;
}
