import type { Locale } from "./content/pages.ts";
import { intendanceExtras, intendanceFaq, intendancePlans, intendanceSetup, intendanceSlug } from "./content/intendance.ts";
import { arrow, contactPath, escape, path, t } from "./lib.ts";
import { faq } from "./components.ts";

function homePhoto(locale: Locale, className: string, priority = false): string {
  return `<picture class="${className}"><source type="image/avif" srcset="/images/villa_amichi-480.avif 480w, /images/villa_amichi-800.avif 800w, /images/villa_amichi-1200.avif 1200w" sizes="(min-width: 1000px) 50vw, 100vw"><img src="/images/villa_amichi-800.webp" srcset="/images/villa_amichi-480.webp 480w, /images/villa_amichi-800.webp 800w, /images/villa_amichi-1200.webp 1200w" sizes="(min-width: 1000px) 50vw, 100vw" width="1200" height="805" alt="${t(locale, "La terrasse et la piscine de la Villa d’Amichi, à Pinarello, une maison du portfolio Inastia", "The terrace and pool of Villa d’Amichi in Pinarello, a home in Inastia’s portfolio")}" ${priority ? 'fetchpriority="high" loading="eager"' : 'loading="lazy"'} decoding="async"></picture>`;
}

export function intendanceTeaser(locale: Locale): string {
  return `<section class="intendance-teaser" aria-labelledby="intendance-teaser-title"><div class="container intendance-teaser-grid">
    <figure>${homePhoto(locale, "intendance-teaser-photo")}<figcaption>Villa d’Amichi · Pinarello</figcaption></figure>
    <div class="intendance-teaser-copy" data-reveal><p class="eyebrow">${t(locale, "INTENDANCE DE RÉSIDENCE SECONDAIRE", "SECOND-HOME CARE")}</p><h2 id="intendance-teaser-title">${t(locale, "Votre résidence secondaire.<br><em>Le suivi, même en votre absence.</em>", "Your second home.<br><em>We take care of the details.</em>")}</h2><p>${t(locale, "Visites régulières, aération, courrier et comptes rendus photo : notre équipe prend le relais en votre absence. Vous restez informé de l’état de votre maison et validez les interventions supplémentaires. Découvrez nos formules et les prestations pour préparer vos séjours.", "Regular visits, airing, mail collection and photo reports: our team takes over while you’re away. You stay informed about your home and approve any additional work. Explore our plans and the services available to prepare for your stays.")}</p><p class="intendance-teaser-price">${t(locale, "À partir de", "From")} <strong>${intendancePlans[0].monthly} €</strong> ${t(locale, "TTC / mois", "incl. VAT / month")}<span>${t(locale, `Mise en place : ${intendanceSetup} € TTC · Conditions et suppléments détaillés dans l’offre.`, `Setup: €${intendanceSetup} incl. VAT · See the offer for conditions and extras.`)}</span></p><a class="button button-outline" href="${path(locale, intendanceSlug)}">${t(locale, "Découvrir l’intendance et ses tarifs", "Explore home care and pricing")}${arrow}</a></div>
  </div></section>`;
}

export function intendance(locale: Locale): string {
  const enquiry = contactPath(locale, "intendance");
  const included = [
    t(locale, "Vérifications visuelles des espaces accessibles", "Visual checks of accessible indoor and outdoor areas"),
    t(locale, "Aération, points d’eau et compteurs accessibles", "Airing, accessible water points and meters"),
    t(locale, "Courrier relevé et conservé dans la maison", "Mail collected and kept at your home"),
    t(locale, "Compte rendu photo après chaque passage", "Photo report after every visit"),
    t(locale, "Clés confiées et anomalies signalées", "Key holding and any issues reported to you"),
    t(locale, "Déplacements des visites programmées inclus", "Travel for scheduled visits included"),
  ];
  const ritual = [
    ["01", t(locale, "Avant le premier passage", "Before the first visit"), t(locale, "Nous faisons le point sur votre maison, ses accès et vos habitudes. Clés, consignes et contacts utiles sont réunis dans le dossier du bien. Nous convenons ensuite du calendrier des visites.", "We review your home, its access and your routines. Keys, instructions and useful contacts are recorded in your property file. We then agree the visit schedule with you.")],
    ["02", t(locale, "Pendant vos absences", "While you’re away"), t(locale, "Nous vérifions les ouvrants, les points d’eau et compteurs accessibles, ainsi que les traces apparentes d’humidité ou de fuite. Nous aérons selon vos consignes et relevons le courrier, conservé dans la maison.", "We check doors and windows, accessible water points and meters, and visible signs of damp or leaks. We air the home following your instructions and collect the mail, which stays at the property.")],
    ["03", t(locale, "Après chaque visite", "After every visit"), t(locale, "Vous recevez des photos et le compte rendu des vérifications. Si nous constatons une anomalie, nous vous la signalons et examinons avec vous les suites à donner. Vous validez les dépenses avant toute intervention supplémentaire.", "You receive photos and a report of the checks completed. If we find an issue, we let you know and discuss the next steps with you. You approve the cost before any additional work is arranged.")],
  ];
  const serviceSchema = {
    "@context": "https://schema.org", "@type": "Service",
    name: t(locale, "Intendance de résidence secondaire en Corse", "Second-home care in Corsica"),
    serviceType: t(locale, "Visites et intendance de résidence secondaire", "Second-home visits and care"),
    provider: { "@type": "Organization", name: "Inastia", url: "https://inastia.fr" },
    url: `https://inastia.fr${path(locale, intendanceSlug)}`,
    areaServed: ["Ghisonaccia", "Ventiseri", "Solenzara", "Sainte-Lucie-de-Porto-Vecchio", "Lecci", "Porto-Vecchio"],
    description: t(locale, "Intendance de résidence secondaire : visites régulières, vérifications visuelles, aération, courrier et comptes rendus photo. Préparation des séjours et interventions complémentaires sur devis.", "Second-home care with regular visits, visual checks, airing, mail collection and photo reports. Stay preparation and additional services are quoted separately."),
  };
  return `<div class="intendance-page"><script type="application/ld+json">${JSON.stringify(serviceSchema).replace(/</g, "\\u003c")}</script>
  <section class="intendance-hero container">
    <div class="intendance-hero-copy"><nav class="breadcrumb" aria-label="${t(locale, "Fil d’Ariane", "Breadcrumb")}"><a href="${path(locale)}">${t(locale, "Accueil", "Home")}</a><span aria-hidden="true">/</span><span>${t(locale, "Intendance", "Home care")}</span></nav><p class="eyebrow">${t(locale, "INTENDANCE DE RÉSIDENCE SECONDAIRE", "SECOND-HOME CARE IN CORSICA")}</p><h1>${t(locale, "Votre résidence secondaire,<br><em>suivie toute l’année.</em>", "Your second home,<br><em>cared for all year.</em>")}</h1><p class="intendance-lead">${t(locale, "Visites régulières, aération, courrier et comptes rendus photo : notre équipe familiale prend le relais auprès de votre résidence secondaire en Corse. Vous savez ce qui a été vérifié et vous décidez des interventions à engager. Préparation de vos séjours, ménage ou rendez-vous avec un artisan : les prestations complémentaires sont organisées sur devis, avec votre accord.", "Regular visits, airing, mail collection and photo reports: our family team looks after your second home in Corsica while you’re away. You know what has been checked and decide which additional work to approve. Arrival preparation, cleaning and contractor appointments are arranged as separately quoted services.")}</p><div class="intendance-hero-actions"><a class="button" href="${enquiry}">${t(locale, "Confier l’intendance de ma maison", "Arrange care for my home")}${arrow}</a><a class="text-link" href="#tarifs-intendance">${t(locale, "Comparer les formules", "Compare the plans")} ↓</a></div><p class="intendance-hero-note">${t(locale, "De Ghisonaccia à Porto-Vecchio. Premier échange et devis gratuits.", "From Ghisonaccia to Porto-Vecchio. Free initial conversation and quote.")}</p></div>
    <figure class="intendance-hero-figure">${homePhoto(locale, "intendance-hero-photo", true)}<div class="intendance-photo-label" aria-hidden="true"><span>INASTIA</span><p>${t(locale, "Votre maison<br>en Corse.<br>Une équipe<br>sur place.", "Your home<br>in Corsica.<br>A local<br>team.")}</p><span>42° N · 09° E</span></div><figcaption>Villa d’Amichi · Pinarello<span>${t(locale, "Une maison de notre portfolio", "A home from our portfolio")}</span></figcaption></figure>
  </section>
  <div class="intendance-at-a-glance container"><p>${t(locale, "Le suivi de votre maison, organisé.", "A clear plan for your home.")}</p><span>${t(locale, "1 ou 2 visites par mois", "1 or 2 visits per month")}</span><span>${t(locale, "Des photos après chaque visite", "Photos after every visit")}</span><span>${t(locale, "Vos dépenses, votre accord", "You approve additional costs")}</span></div>
  <section class="section intendance-ritual"><div class="container"><div class="intendance-section-heading" data-reveal><p class="eyebrow">${t(locale, "CE QUE NOUS PRENONS EN CHARGE", "WHAT WE TAKE CARE OF")}</p><h2>${t(locale, "Nous suivons votre maison.<br><em>Vous restez informé.</em>", "We check your home.<br><em>You stay informed.</em>")}</h2><p>${t(locale, "Vous n’avez plus à organiser chaque passage ni à chercher quelqu’un pour relever le courrier. Nous planifions les visites, réalisons les vérifications convenues et vous transmettons les informations utiles pour décider des suites.", "You no longer need to arrange each visit or find someone to collect the mail. We schedule the visits, carry out the agreed checks and give you the information you need to decide what happens next.")}</p></div><ol class="intendance-ritual-grid">${ritual.map(([number, title, copy]) => `<li data-reveal><span class="intendance-step-number" aria-hidden="true">${number}</span><h3>${title}</h3><p>${copy}</p></li>`).join("")}</ol></div></section>
  <section class="section intendance-plans-section" id="tarifs-intendance" aria-labelledby="intendance-pricing-title"><div class="container"><div class="intendance-section-heading" data-reveal><p class="eyebrow">${t(locale, "LES FORMULES D’INTENDANCE", "HOME-CARE PLANS")}</p><h2 id="intendance-pricing-title">${t(locale, "Une fréquence choisie.<br><em>Un forfait mensuel.</em>", "Choose the frequency.<br><em>Know the monthly cost.</em>")}</h2><p>${t(locale, "Choisissez un ou deux passages par mois. Chaque formule comprend les vérifications convenues, la garde des clés et un compte rendu photo. Les préparations de séjour et les interventions spécifiques se choisissent en complément.", "Choose one or two visits a month. Both plans include the agreed checks, key holding and a photo report. Stay preparation and specific interventions are available as additional services.")}</p></div>
    <div class="intendance-plans">${intendancePlans.map((plan, index) => `<article class="intendance-plan ${index ? "intendance-plan-deep" : ""}" aria-labelledby="plan-${plan.id}" data-reveal><div class="intendance-plan-top"><span class="eyebrow">${t(locale, "LE SUIVI DE VOTRE MAISON", "CARE FOR YOUR HOME")}</span><span class="intendance-plan-count">0${plan.visits}</span></div><h3 id="plan-${plan.id}">${plan.name[locale]}</h3><p class="intendance-plan-rhythm">${plan.visits} ${t(locale, plan.visits === 1 ? "visite programmée par mois" : "visites programmées par mois", plan.visits === 1 ? "scheduled visit per month" : "scheduled visits per month")}</p><p class="intendance-plan-price"><strong>${plan.monthly}<span> €</span></strong><span>${t(locale, "TTC / mois", "incl. VAT / month")}</span></p><p class="intendance-plan-description">${index ? t(locale, "Deux passages répartis dans le mois pour rapprocher les vérifications et le suivi de votre maison.", "Two visits spread across the month for more frequent checks and updates on your home.") : t(locale, "Un passage chaque mois pour vérifier les points convenus et recevoir des nouvelles de votre maison.", "One visit each month to check the agreed points and keep you informed about your home.")}</p><ul>${included.map(item => `<li>${item}</li>`).join("")}</ul><a class="button ${index ? "button-cream" : "button-outline"}" href="${enquiry}&formule=${plan.id}">${t(locale, "Demander", "Request")} ${plan.name[locale]}${arrow}</a><p class="intendance-plan-total">${t(locale, `Pour 12 mois d’abonnement : ${(plan.monthly * 12).toLocaleString("fr-FR")} € TTC, hors mise en place et suppléments.`, `For 12 months of service: €${(plan.monthly * 12).toLocaleString("en-GB")} incl. VAT, excluding setup and extras.`)}</p></article>`).join("")}</div>
    <div class="intendance-setup"><div><span class="eyebrow">${t(locale, "LA MISE EN PLACE DU SUIVI", "GETTING STARTED")}</span><h3>${t(locale, "Nous préparons<br>le suivi de votre maison.", "We prepare<br>your home-care plan.")}</h3></div><p>${t(locale, "Nous visitons le logement, recueillons vos consignes et organisons les clés pour préparer les passages. Cette mise en place est réalisée après acceptation du devis. Le premier échange et le devis sont gratuits.", "We visit the property, record your instructions and arrange the keys before scheduled care begins. Setup takes place after you accept the quote. The initial conversation and quote are free.")}</p><p class="intendance-setup-price"><strong>${intendanceSetup} €</strong><span>${t(locale, "TTC, une seule fois", "incl. VAT, once only")}</span></p></div>
    <p class="intendance-price-scope">${t(locale, "Tarifs pour un logement jusqu’à 150 m², dans un seul bâtiment, avec accès routier standard sur notre secteur confirmé au devis. Visites jusqu’à 30 minutes, déplacements programmés et comptes rendus inclus. Abonnement mensuel, sans engagement annuel, résiliable avec 30 jours de préavis.", "Prices cover one home of up to 150 m² in a single building, with standard road access in the service area confirmed in your quote. Visits of up to 30 minutes, scheduled travel and reports included. Monthly subscription, no annual commitment, cancellable with 30 days’ notice.")} <a href="/cgv#intendance" lang="fr">${t(locale, "Conditions d’intendance", "Home-care terms (French)")} ↗</a></p>
    <div class="intendance-bespoke"><p><strong>${t(locale, "Votre maison demande un suivi particulier ?", "Does your home need a different level of care?")}</strong><br>${t(locale, "Grande surface, dépendances, accès isolé ou visites plus fréquentes : nous définissons avec vous les passages nécessaires et leur coût dans un devis adapté.", "A larger home, outbuildings, isolated access or more frequent visits: we agree the care required and its cost in a tailored quote.")}</p><a class="text-link" href="${enquiry}&formule=surmesure">${t(locale, "Recevoir un devis sur mesure", "Request a tailored quote")}${arrow}</a></div>
  </div></section>
  <section class="section intendance-extras" aria-labelledby="intendance-extras-title"><div class="container intendance-extras-layout"><div class="intendance-extras-intro" data-reveal><p class="eyebrow">${t(locale, "LES PRESTATIONS EN COMPLÉMENT", "ADDITIONAL SERVICES")}</p><h2 id="intendance-extras-title">${t(locale, "Préparer votre arrivée.<br><em>Organiser les interventions.</em>", "Prepare for your arrival.<br><em>Arrange work at your home.</em>")}</h2><p>${t(locale, "Vous préparez un séjour en Corse ou une intervention dans votre maison ? Nous organisons les prestations dont vous avez besoin : ouverture, fermeture, visite supplémentaire ou présence sur place. Vous connaissez le contenu et le coût avant de confirmer.", "Planning a stay in Corsica or work at your home? We arrange the services you need: arrival preparation, closing up, an extra visit or meeting someone on site. You know what is included and what it costs before confirming.")}</p><p class="intendance-extras-note">${t(locale, "Prix TTC, réservés aux maisons suivies en intendance. Le coût et le créneau sont convenus avant chaque prestation.", "Prices include VAT and apply to homes on a home-care plan. Cost and timing are agreed before each service.")}</p></div><div class="intendance-extra-list">${intendanceExtras.map(extra => `<article class="intendance-extra" data-reveal><div><h3>${escape(extra.name[locale])}</h3><p>${escape(extra.detail[locale])}</p></div><p class="intendance-extra-price"><strong>${extra.price} €</strong><span>${extra.unit[locale]}</span></p></article>`).join("")}<div class="intendance-contractors"><h3>${t(locale, "Ménage, linge, jardin, piscine et travaux", "Cleaning, linen, gardens, pools and repairs")}</h3><p>${t(locale, "Nous organisons ces prestations selon les besoins de votre maison. Le ménage, le linge, l’entretien extérieur et les travaux sont chiffrés sur des devis distincts. Les achats et les professionnels restent à votre charge ; les éventuels frais de coordination spécifique sont annoncés avant votre accord.", "We arrange these services around your home’s needs. Cleaning, linen, outdoor maintenance and building work are quoted separately. Purchases and professional fees remain at your expense; any additional coordination charge is set out before you approve it.")}</p></div></div></div></section>
  <section class="intendance-region"><div class="container intendance-region-grid"><div><p class="eyebrow">${t(locale, "UNE ÉQUIPE LOCALE POUR VOTRE MAISON", "A LOCAL TEAM FOR YOUR HOME")}</p><h2>${t(locale, "De Ghisonaccia<br><em>à Porto-Vecchio.</em>", "From Ghisonaccia<br><em>to Porto-Vecchio.</em>")}</h2><p>${t(locale, "Notre équipe familiale suit les maisons de la côte orientale, en passant par Ventiseri, Solenzara, Sainte-Lucie-de-Porto-Vecchio, Pinarello et Lecci. Nous vérifions votre adresse précise et les accès avant de confirmer les visites et leur organisation.", "Our family team cares for homes along the east coast, including Ventiseri, Solenzara, Sainte-Lucie-de-Porto-Vecchio, Pinarello and Lecci. We check your exact address and access before confirming the visits and their schedule.")}</p></div><div class="intendance-region-line" aria-hidden="true"><span>Ghisonaccia</span><i></i><span>Ventiseri · Solenzara</span><i></i><span>Pinarello · Lecci</span><i></i><span>Porto-Vecchio</span></div></div></section>
  ${faq(locale, intendanceFaq[locale])}
  <section class="intendance-closing"><div class="container"><p class="eyebrow">${t(locale, "VOTRE PROPOSITION D’INTENDANCE", "YOUR HOME-CARE PROPOSAL")}</p><h2>${t(locale, "Confiez-nous les clés.<br><em>Nous suivons votre maison.</em>", "Hand us the keys.<br><em>We look after your home.</em>")}</h2><p>${t(locale, "Indiquez-nous où se trouve votre maison, vos périodes de présence et le suivi souhaité. Nous définissons avec vous les visites, les prestations complémentaires et leurs coûts. Vous recevez une proposition détaillée et examinez les conditions avant de vous engager.", "Tell us where your home is, when you stay and what care you need. We agree the visits, additional services and their costs with you. You receive a detailed proposal and review the terms before committing.")}</p><a class="button" href="${enquiry}">${t(locale, "Confier l’intendance de ma maison", "Arrange care for my home")}${arrow}</a><a class="intendance-closing-phone" href="tel:+33613812550">+33 6 13 81 25 50</a><p class="intendance-rental-link">${t(locale, "Vous souhaitez nous confier aussi vos locations ?", "Would you also like us to manage your rentals?")} <a href="${path(locale, "gestion-airbnb-corse-du-sud")}">${t(locale, "Découvrir la gestion complète", "Explore full management")} ↗</a></p></div></section></div>`;
}
