import type { Locale } from "./content/pages.ts";
import { intendanceExtras, intendanceFaq, intendancePlans, intendanceSetup, intendanceSlug } from "./content/intendance.ts";
import { arrow, contactPath, escape, path, t } from "./lib.ts";
import { faq } from "./components.ts";

function homePhoto(locale: Locale, className: string, priority = false): string {
  return `<picture class="${className}"><source type="image/avif" srcset="/images/villa_amichi-480.avif 480w, /images/villa_amichi-800.avif 800w, /images/villa_amichi-1200.avif 1200w" sizes="(min-width: 1000px) 50vw, 100vw"><img src="/images/villa_amichi-800.webp" srcset="/images/villa_amichi-480.webp 480w, /images/villa_amichi-800.webp 800w, /images/villa_amichi-1200.webp 1200w" sizes="(min-width: 1000px) 50vw, 100vw" width="1200" height="805" alt="${t(locale, "La terrasse et la piscine de la Villa d’Amichi, à Pinarello, une maison du portfolio Inastia", "The terrace and pool of Villa d’Amichi in Pinarello, a home in Inastia’s portfolio")}" ${priority ? 'fetchpriority="high" loading="eager"' : 'loading="lazy"'} decoding="async"></picture>`;
}

export function intendanceTeaser(locale: Locale): string {
  return `<section class="intendance-teaser" aria-labelledby="intendance-teaser-title"><div class="container intendance-teaser-grid">
    <figure>${homePhoto(locale, "intendance-teaser-photo")}<figcaption>Villa d’Amichi · Pinarello</figcaption></figure>
    <div class="intendance-teaser-copy" data-reveal><p class="eyebrow">${t(locale, "INTENDANCE DE RÉSIDENCE SECONDAIRE", "SECOND-HOME CARE")}</p><h2 id="intendance-teaser-title">${t(locale, "Votre maison.<br><em>Même quand vous êtes loin.</em>", "Your home.<br><em>Cared for while you’re away.</em>")}</h2><p>${t(locale, "Vous gardez votre maison pour vos séjours ? Nous passons, vérifions et vous tenons informé. Une présence locale toute l’année, sans confier votre bien à la location.", "Keeping your home for your own stays? We visit, check and keep you informed. A local presence throughout the year, without handing your home over for rental.")}</p><p class="intendance-teaser-price">${t(locale, "À partir de", "From")} <strong>${intendancePlans[0].monthly} €</strong> ${t(locale, "TTC / mois", "incl. VAT / month")}<span>${t(locale, `Mise en place : ${intendanceSetup} € TTC · Conditions et suppléments détaillés dans l’offre.`, `Setup: €${intendanceSetup} incl. VAT · See the offer for conditions and extras.`)}</span></p><a class="button button-outline" href="${path(locale, intendanceSlug)}">${t(locale, "Découvrir l’intendance et ses tarifs", "Explore home care and pricing")}${arrow}</a></div>
  </div></section>`;
}

export function intendance(locale: Locale): string {
  const enquiry = contactPath(locale, "intendance");
  const included = [
    t(locale, "Contrôle visuel intérieur et extérieur accessible", "Visual checks inside and in accessible outdoor areas"),
    t(locale, "Aération, points d’eau et compteurs accessibles", "Airing, accessible water points and meters"),
    t(locale, "Relève du courrier et conservation sur place", "Collecting mail and keeping it at the property"),
    t(locale, "Compte rendu photo après chaque passage", "A photo report after every visit"),
    t(locale, "Garde des clés et signalement des anomalies", "Key holding and reporting any issues found"),
  ];
  const ritual = [
    ["01", t(locale, "Nous passons.", "We visit."), t(locale, "Un calendrier convenu, les consignes de votre maison et une visite attentive des espaces accessibles.", "An agreed schedule, your property’s instructions and a careful visit of accessible areas.")],
    ["02", t(locale, "Nous regardons.", "We check."), t(locale, "Une trace d’humidité, un point d’eau, un volet : nous relevons ce qui mérite votre attention.", "Signs of damp, a water point, a shutter: we note anything that needs your attention.")],
    ["03", t(locale, "Vous savez.", "You know."), t(locale, "Des photos, un compte rendu et, si nécessaire, les suites à décider ensemble. Vous gardez la main.", "Photos, a report and, when needed, next steps to agree together. You stay in control.")],
  ];
  const serviceSchema = {
    "@context": "https://schema.org", "@type": "Service",
    name: t(locale, "Intendance de résidence secondaire en Corse", "Second-home care in Corsica"),
    serviceType: t(locale, "Visites et intendance de résidence secondaire", "Second-home visits and care"),
    provider: { "@type": "Organization", name: "Inastia", url: "https://inastia.fr" },
    url: `https://inastia.fr${path(locale, intendanceSlug)}`,
    areaServed: ["Ghisonaccia", "Ventiseri", "Solenzara", "Sainte-Lucie-de-Porto-Vecchio", "Lecci", "Porto-Vecchio"],
    description: t(locale, "Visites programmées, compte rendu photo et suivi de votre résidence secondaire. Forfaits mensuels et prestations complémentaires sur devis.", "Scheduled visits, photo reports and care for your second home. Monthly plans and separately quoted additional services."),
  };
  return `<div class="intendance-page"><script type="application/ld+json">${JSON.stringify(serviceSchema).replace(/</g, "\\u003c")}</script>
  <section class="intendance-hero container">
    <div class="intendance-hero-copy"><nav class="breadcrumb" aria-label="${t(locale, "Fil d’Ariane", "Breadcrumb")}"><a href="${path(locale)}">${t(locale, "Accueil", "Home")}</a><span aria-hidden="true">/</span><span>${t(locale, "Intendance", "Home care")}</span></nav><p class="eyebrow">${t(locale, "VOTRE RÉSIDENCE SECONDAIRE EN CORSE", "YOUR SECOND HOME IN CORSICA")}</p><h1>${t(locale, "L’esprit ici.<br>La maison<br><em>entre de bonnes mains.</em>", "Your place here.<br>Your home<br><em>in good hands.</em>")}</h1><p class="intendance-lead">${t(locale, "Vous êtes loin. Votre maison reste entourée d’attention. Nous veillons à son suivi, préparons vos retours et vous donnons des nouvelles, au fil des saisons.", "You’re away. Your home still receives care and attention. We look after it, prepare for your return and keep you informed, through every season.")}</p><div class="intendance-hero-actions"><a class="button" href="${enquiry}">${t(locale, "Parlons de ma maison", "Let’s talk about my home")}${arrow}</a><a class="text-link" href="#tarifs-intendance">${t(locale, "Voir les formules", "View the plans")} ↓</a></div><p class="intendance-hero-note">${t(locale, "Une équipe familiale, de Ghisonaccia à Porto-Vecchio.", "A family team, from Ghisonaccia to Porto-Vecchio.")}</p></div>
    <figure class="intendance-hero-figure">${homePhoto(locale, "intendance-hero-photo", true)}<div class="intendance-photo-label" aria-hidden="true"><span>INASTIA</span><p>${t(locale, "Le plaisir<br>de retrouver<br>sa maison.", "The joy<br>of coming<br>home.")}</p><span>42° N · 09° E</span></div><figcaption>Villa d’Amichi · Pinarello<span>${t(locale, "Une maison de notre portfolio", "A home from our portfolio")}</span></figcaption></figure>
  </section>
  <div class="intendance-at-a-glance container"><p>${t(locale, "Votre maison, à votre rythme.", "Your home, at your pace.")}</p><span>${t(locale, "1 ou 2 visites par mois", "1 or 2 visits per month")}</span><span>${t(locale, "Un compte rendu photo", "A photo report")}</span><span>${t(locale, "Un lien direct", "A direct point of contact")}</span></div>
  <section class="section intendance-ritual"><div class="container"><div class="intendance-section-heading" data-reveal><p class="eyebrow">${t(locale, "UNE PRÉSENCE QUI COMPTE", "A PRESENCE THAT MATTERS")}</p><h2>${t(locale, "Les petits détails.<br><em>Votre tranquillité.</em>", "The little details.<br><em>Your peace of mind.</em>")}</h2><p>${t(locale, "La maison que vous retrouvez quelques semaines par an a besoin d’attention le reste du temps. Nous lui consacrons des passages réguliers, selon les consignes définies ensemble.", "The home you enjoy for a few weeks each year needs attention the rest of the time. We make regular visits, following the instructions we agree together.")}</p></div><ol class="intendance-ritual-grid">${ritual.map(([number, title, copy]) => `<li data-reveal><span class="intendance-step-number" aria-hidden="true">${number}</span><h3>${title}</h3><p>${copy}</p></li>`).join("")}</ol></div></section>
  <section class="section intendance-plans-section" id="tarifs-intendance" aria-labelledby="intendance-pricing-title"><div class="container"><div class="intendance-section-heading" data-reveal><p class="eyebrow">${t(locale, "LES FORMULES D’INTENDANCE", "HOME-CARE PLANS")}</p><h2 id="intendance-pricing-title">${t(locale, "Le bon rythme.<br><em>Un prix clair.</em>", "The right rhythm.<br><em>A clear price.</em>")}</h2><p>${t(locale, "Deux formules pour suivre votre maison toute l’année. La même attention, une fréquence de passage adaptée à vos besoins.", "Two plans to care for your home throughout the year. The same attention, with a frequency that suits your needs.")}</p></div>
    <div class="intendance-plans">${intendancePlans.map((plan, index) => `<article class="intendance-plan ${index ? "intendance-plan-deep" : ""}" aria-labelledby="plan-${plan.id}" data-reveal><div class="intendance-plan-top"><span class="eyebrow">${t(locale, "LE SUIVI DE VOTRE MAISON", "CARE FOR YOUR HOME")}</span><span class="intendance-plan-count">0${plan.visits}</span></div><h3 id="plan-${plan.id}">${plan.name[locale]}</h3><p class="intendance-plan-rhythm">${plan.visits} ${t(locale, plan.visits === 1 ? "visite programmée par mois" : "visites programmées par mois", plan.visits === 1 ? "scheduled visit per month" : "scheduled visits per month")}</p><p class="intendance-plan-price"><strong>${plan.monthly}<span> €</span></strong><span>${t(locale, "TTC / mois", "incl. VAT / month")}</span></p><p class="intendance-plan-description">${index ? t(locale, "Pour garder un contact plus régulier avec votre maison entre deux séjours.", "For more regular attention to your home between stays.") : t(locale, "Pour garder un lien avec votre maison et être informé de son état.", "To stay connected to your home and informed about its condition.")}</p><ul>${included.map(item => `<li>${item}</li>`).join("")}</ul><a class="button ${index ? "button-cream" : "button-outline"}" href="${enquiry}&formule=${plan.id}">${t(locale, "Choisir", "Choose")} ${plan.name[locale]}${arrow}</a><p class="intendance-plan-total">${t(locale, `Si vous restez 12 mois : ${(plan.monthly * 12).toLocaleString("fr-FR")} € TTC, hors mise en place et suppléments.`, `If you stay for 12 months: €${(plan.monthly * 12).toLocaleString("en-GB")} incl. VAT, excluding setup and extras.`)}</p></article>`).join("")}</div>
    <div class="intendance-setup"><div><span class="eyebrow">${t(locale, "POUR BIEN COMMENCER", "A THOUGHTFUL START")}</span><h3>${t(locale, "Nous faisons connaissance<br>avec votre maison.", "We get to know<br>your home.")}</h3></div><p>${t(locale, "Visite initiale, consignes, dossier du bien et organisation des clés. Le premier échange et le devis sont gratuits ; la mise en place débute après votre accord.", "Initial visit, instructions, property file and key arrangements. The first conversation and quote are free; setup begins after your approval.")}</p><p class="intendance-setup-price"><strong>${intendanceSetup} €</strong><span>${t(locale, "TTC, une seule fois", "incl. VAT, once only")}</span></p></div>
    <p class="intendance-price-scope">${t(locale, "Tarifs pour un logement jusqu’à 150 m², dans un seul bâtiment, avec accès routier standard sur notre secteur confirmé au devis. Visites jusqu’à 30 minutes, déplacements programmés et comptes rendus inclus. Abonnement mensuel, sans engagement annuel, résiliable avec 30 jours de préavis.", "Prices cover one home of up to 150 m² in a single building, with standard road access in the service area confirmed in your quote. Visits of up to 30 minutes, scheduled travel and reports included. Monthly subscription, no annual commitment, cancellable with 30 days’ notice.")} <a href="/cgv#intendance" lang="fr">${t(locale, "Conditions d’intendance", "Home-care terms (French)")} ↗</a></p>
    <div class="intendance-bespoke"><p><strong>${t(locale, "Une grande propriété ou un rythme différent ?", "A larger property or a different rhythm?")}</strong><br>${t(locale, "Au-delà de 150 m², avec dépendances, accès isolé ou besoin de passages plus fréquents : nous établissons un devis adapté.", "Over 150 m², outbuildings, isolated access or more frequent visits: we prepare a tailored quote.")}</p><a class="text-link" href="${enquiry}&formule=surmesure">${t(locale, "Étudier ma maison", "Discuss my home")}${arrow}</a></div>
  </div></section>
  <section class="section intendance-extras" aria-labelledby="intendance-extras-title"><div class="container intendance-extras-layout"><div class="intendance-extras-intro" data-reveal><p class="eyebrow">${t(locale, "SELON VOS BESOINS", "WHEN YOU NEED MORE")}</p><h2 id="intendance-extras-title">${t(locale, "Votre séjour<br>se prépare.<br><em>Nous aussi.</em>", "You’re getting<br>ready to return.<br><em>So are we.</em>")}</h2><p>${t(locale, "Un retour en Corse, un artisan à recevoir, un passage supplémentaire : complétez votre abonnement avec les prestations utiles à votre maison.", "Returning to Corsica, meeting a contractor or arranging another visit: add the services your home needs to your subscription.")}</p><p class="intendance-extras-note">${t(locale, "Prix TTC, réservés aux maisons suivies en intendance. Le coût et le créneau sont convenus avant chaque prestation.", "Prices include VAT and apply to homes on a home-care plan. Cost and timing are agreed before each service.")}</p></div><div class="intendance-extra-list">${intendanceExtras.map(extra => `<article class="intendance-extra" data-reveal><div><h3>${escape(extra.name[locale])}</h3><p>${escape(extra.detail[locale])}</p></div><p class="intendance-extra-price"><strong>${extra.price} €</strong><span>${extra.unit[locale]}</span></p></article>`).join("")}<div class="intendance-contractors"><h3>${t(locale, "Ménage, linge, jardin, piscine et travaux", "Cleaning, linen, gardens, pools and repairs")}</h3><p>${t(locale, "Sur devis distinct selon la surface, les équipements et l’intervention. Les prestations des professionnels et les achats restent à votre charge. Toute coordination spécifique est chiffrée séparément et soumise à votre accord.", "Quoted separately according to size, facilities and the work required. Professional services and purchases remain at your expense. Any specific coordination is priced separately and requires your approval.")}</p></div></div></div></section>
  <section class="intendance-region"><div class="container intendance-region-grid"><div><p class="eyebrow">${t(locale, "NOTRE CÔTE, VOTRE MAISON", "OUR COAST, YOUR HOME")}</p><h2>${t(locale, "De Ghisonaccia<br><em>à Porto-Vecchio.</em>", "From Ghisonaccia<br><em>to Porto-Vecchio.</em>")}</h2><p>${t(locale, "Ventiseri, Solenzara, Sainte-Lucie-de-Porto-Vecchio, Pinarello, Lecci… Votre adresse et les accès nous permettent de confirmer la prise en charge et d’organiser les tournées.", "Ventiseri, Solenzara, Sainte-Lucie-de-Porto-Vecchio, Pinarello, Lecci… Your address and access details let us confirm service and plan our rounds.")}</p></div><div class="intendance-region-line" aria-hidden="true"><span>Ghisonaccia</span><i></i><span>Ventiseri · Solenzara</span><i></i><span>Pinarello · Lecci</span><i></i><span>Porto-Vecchio</span></div></div></section>
  ${faq(locale, intendanceFaq[locale])}
  <section class="intendance-closing"><div class="container"><p class="eyebrow">${t(locale, "IL SUFFIT D’UN PREMIER ÉCHANGE", "IT STARTS WITH A CONVERSATION")}</p><h2>${t(locale, "Vous avez une maison ici.<br><em>Vous avez quelqu’un sur place.</em>", "You have a home here.<br><em>You have someone nearby.</em>")}</h2><p>${t(locale, "Présentez-nous votre maison et vos habitudes. Nous vous proposerons un suivi adapté, avec un devis détaillé avant toute décision.", "Tell us about your home and your routines. We’ll suggest the right care, with a detailed quote before you decide.")}</p><a class="button" href="${enquiry}">${t(locale, "Préparer l’intendance de ma maison", "Arrange care for my home")}${arrow}</a><a class="intendance-closing-phone" href="tel:+33613812550">+33 6 13 81 25 50</a><p class="intendance-rental-link">${t(locale, "Vous souhaitez aussi déléguer vos locations ?", "Would you also like to delegate your rentals?")} <a href="${path(locale, "gestion-airbnb-corse-du-sud")}">${t(locale, "Découvrir la gestion complète", "Explore full management")} ↗</a></p></div></section></div>`;
}
