import type { Locale } from "./content/pages.ts";
import { partnerFaq, partnerMail, partnerProfiles } from "./content/partners.ts";
import { intendanceSlug } from "./content/intendance.ts";
import { arrow, escape, path, t } from "./lib.ts";

function partnerPhoto(name: string, alt: string, priority = false): string {
  return `<picture><source type="image/avif" srcset="/images/${name}-480.avif 480w, /images/${name}-800.avif 800w, /images/${name}-1200.avif 1200w" sizes="(min-width: 1024px) 54vw, 100vw"><img src="/images/${name}-800.webp" srcset="/images/${name}-480.webp 480w, /images/${name}-800.webp 800w, /images/${name}-1200.webp 1200w" sizes="(min-width: 1024px) 54vw, 100vw" width="1200" height="805" alt="${escape(alt)}" loading="${priority ? "eager" : "lazy"}" ${priority ? 'fetchpriority="high"' : ""} decoding="async"></picture>`;
}

function partnerIllustration(locale: Locale): string {
  return `<picture><source type="image/avif" srcset="/images/inastia-partners-home-480.avif 480w, /images/inastia-partners-home-800.avif 800w, /images/inastia-partners-home-1122.avif 1122w" sizes="(min-width: 700px) 44vw, calc(100vw - 48px)"><img src="/images/inastia-partners-home-800.webp" srcset="/images/inastia-partners-home-480.webp 480w, /images/inastia-partners-home-800.webp 800w, /images/inastia-partners-home-1122.webp 1122w" sizes="(min-width: 700px) 44vw, calc(100vw - 48px)" width="1122" height="1402" alt="${t(locale, "Illustration d’une maison corse en pierre, entourée d’oliviers, avec une piscine et la mer en arrière-plan", "Illustration of a Corsican stone home among olive trees, with a swimming pool and the sea in the background")}" loading="lazy" decoding="async"></picture>`;
}

const connectionMark = `<svg viewBox="0 0 80 80" fill="none" aria-hidden="true"><path d="M40 12v56M12 40h56M20 20l40 40M20 60l40-40" stroke="currentColor" stroke-width="1.2"/><circle cx="40" cy="40" r="20" stroke="currentColor" stroke-width="1.2"/><circle cx="40" cy="40" r="6" fill="currentColor"/></svg>`;

export function partners(locale: Locale): string {
  const profiles = partnerProfiles[locale];
  const steps = locale === "fr" ? [
    ["Vous présentez votre activité.", "Votre métier, votre secteur et votre intention nous donnent un point de départ. Il n’est pas nécessaire de transmettre les coordonnées d’un propriétaire pour faire connaissance."],
    ["Nous précisons le cadre.", "Nous échangeons sur le besoin, le rôle de chacun et les conditions applicables à la collaboration envisagée."],
    ["Une collaboration peut être convenue.", "Selon le projet retenu, il peut s’agir d’une prestation ou d’une mise en relation. Le premier échange sert à examiner les possibilités ; il ne présume pas de la suite."],
  ] : [
    ["Tell us about your work.", "Your activity, relevant area and intention give us a starting point. You do not need to share a homeowner’s contact details for this first conversation."],
    ["We clarify the terms.", "We discuss the need, everyone’s role and the terms that would apply to the proposed collaboration."],
    ["A collaboration may be agreed.", "Depending on the project, this could be a service or an introduction. The first conversation explores possibilities; it does not guarantee what happens next."],
  ];
  return `<div class="partners-page">
    <section class="partners-hero" aria-labelledby="partners-title">
      <div class="partners-hero-copy">
        <nav class="breadcrumb" aria-label="${t(locale, "Fil d’Ariane", "Breadcrumb")}"><a href="${path(locale)}">${t(locale, "Accueil", "Home")}</a><span aria-hidden="true">/</span><span>${t(locale, "Partenaires", "Partners")}</span></nav>
        <p class="eyebrow"><span class="partners-dot" aria-hidden="true"></span>${t(locale, "PARTENARIATS · INASTIA", "PARTNERSHIPS · INASTIA")}</p>
        <h1 id="partners-title">${t(locale, "Recommander Inastia ou proposer vos services :<br><em>parlons partenariat.</em>", "Recommend Inastia or offer your services.<br><em>Let’s work together.</em>")}</h1>
        <p class="partners-lead">${t(locale, "Vous accompagnez des propriétaires, vous intervenez dans les maisons ou vous connaissez quelqu’un qui cherche une équipe sur place ? Découvrez comment collaborer avec Inastia autour de la gestion locative et de l’intendance, sur la côte orientale de la Corse.", "Do you work with homeowners, provide home services or know someone looking for local support? Explore working with Inastia on rental management and second-home care along Corsica’s east coast.")}</p>
        <div class="partners-hero-actions"><a class="button" data-partner-profile="general" data-contact-placement="hero" href="${partnerMail(locale)}">${t(locale, "Présenter mon activité par email", "Introduce my business by email")}${arrow}</a><a class="partners-discover" href="#collaborations">${t(locale, "Voir les collaborations", "Explore the collaborations")}<span aria-hidden="true">↓</span></a></div>
        <p class="partners-hero-help">${t(locale, "Votre activité, votre secteur, la collaboration envisagée. Le bouton prépare un message à compléter puis à envoyer dans votre messagerie.", "Your work, relevant area and proposed collaboration. The button prepares an email for you to complete and send in your email app.")}</p>
        <p class="partners-hero-location">${t(locale, "UNE ÉQUIPE FAMILIALE, INSTALLÉE À TRAVO.", "A FAMILY TEAM, BASED IN TRAVO.")}<span>Ghisonaccia — Porto-Vecchio</span></p>
      </div>
      <figure class="partners-hero-visual">
        ${partnerPhoto("villa_amichi", t(locale, "La terrasse en pierre et la piscine de la Villa d’Amichi, à Pinarello", "The stone terrace and pool at Villa d’Amichi in Pinarello"), true)}
        <div class="partners-photo-label">${t(locale, "CORSE ORIENTALE", "CORSICA’S EAST COAST")} <span>42° N · 09° E</span></div>
        <div class="partners-photo-note">${connectionMark}<p>${t(locale, "Un même territoire.<br><em>Une attention commune.</em>", "A place we share.<br><em>A care we have in common.</em>")}</p></div>
        <figcaption>Villa d’Amichi · Pinarello<span>${t(locale, "Une maison du portfolio Inastia", "A home from the Inastia portfolio")}</span></figcaption>
      </figure>
    </section>

    <div class="partners-values container" role="group" aria-label="${t(locale, "Notre façon de travailler", "Our approach")}"><p><span>01</span>${t(locale, "Un ancrage local", "Local knowledge")}</p><p><span>02</span>${t(locale, "Des rôles clairs", "Clear roles")}</p><p><span>03</span>${t(locale, "Une relation directe", "A direct relationship")}</p></div>

    <section class="partners-section container" id="collaborations" aria-labelledby="collaborations-title">
      <div class="partners-section-heading"><div><p class="eyebrow">${t(locale, "01 / NOS COLLABORATIONS", "01 / WORKING TOGETHER")}</p><h2 id="collaborations-title">${t(locale, "Une collaboration<br><em>qui part de votre métier.</em>", "Working together,<br><em>starting with your expertise.</em>")}</h2></div><p>${t(locale, "Vous vous reconnaissez dans plusieurs situations ? Présentez simplement ce que vous envisagez. Ces entrées vous orientent, sans vous imposer un statut.", "More than one situation sounds like you? Simply tell us what you have in mind. These starting points help you find your way without assigning you a formal status.")}</p></div>
      <div class="partners-profiles">${profiles.map((profile, index) => `<article class="partner-profile"><div class="partner-profile-top"><span>0${index + 1}</span>${connectionMark}</div><p class="eyebrow">${escape(profile.label)}</p><h3>${escape(profile.title)}</h3><div class="partner-profile-text"><p>${escape(profile.text)}</p><p>${escape(profile.next)}</p></div><div class="partner-profile-detail"><p>${escape(profile.detail)}</p><a href="#${profile.detailAnchor}">${escape(profile.detailLink)} <span aria-hidden="true">↓</span></a></div><a class="text-link" data-partner-profile="${profile.id}" data-contact-placement="profile" href="${partnerMail(locale, profile.id)}">${escape(profile.action)}${arrow}</a></article>`).join("")}</div>
    </section>

    <section class="partners-local" id="inastia-concretement" aria-labelledby="partners-local-title"><div class="container partners-local-grid"><figure>${partnerIllustration(locale)}</figure><div class="partners-local-copy"><p class="eyebrow">${t(locale, "02 / INASTIA, CONCRÈTEMENT", "02 / WHAT INASTIA DOES")}</p><h2 id="partners-local-title">${t(locale, "Une équipe familiale.<br><em>Deux besoins, un relais.</em>", "A family team.<br><em>Two needs, one local contact.</em>")}</h2><p>${t(locale, "Installés à Travo, sur la commune de Ventiseri, nous accompagnons les propriétaires de Ghisonaccia à Porto-Vecchio. Propriétaires nous-mêmes, nous avons créé Inastia pour la gestion et le suivi des maisons en Corse. Vous échangez directement avec notre équipe.", "Based in Travo, in the municipality of Ventiseri, we work with owners from Ghisonaccia to Porto-Vecchio. As homeowners ourselves, we created Inastia to manage and look after homes in Corsica. You speak directly with our team.")}</p><div class="partners-service"><h3>${t(locale, "Pour les maisons proposées à la location", "For homes offered as holiday rentals")}</h3><p>${t(locale, "Notre gestion complète couvre les annonces, les réservations, les échanges avec les voyageurs et l’organisation des séjours. Elle comprend aussi la coordination du ménage, du linge et du suivi de la maison.", "Our full management covers listings, bookings, guest communication and stay arrangements, as well as coordinating cleaning, linen and care for the home.")}</p><a class="text-link" href="${path(locale, "gestion-airbnb-corse-du-sud")}">${t(locale, "Découvrir la gestion complète", "Explore full management")}${arrow}</a></div><div class="partners-service"><h3>${t(locale, "Pour les résidences secondaires", "For second homes")}</h3><p>${t(locale, "L’intendance permet de faire suivre une maison pendant les absences de son propriétaire : visites régulières, vérifications convenues, aération, courrier et comptes rendus photo. La préparation des séjours et les interventions complémentaires sont organisées selon les besoins et les conditions convenues.", "Our home care service looks after a property while its owner is away: regular visits, agreed checks, airing, mail collection and photo reports. Stay preparation and additional work are arranged according to the needs and agreed terms.")}</p><a class="text-link" href="${path(locale, intendanceSlug)}">${t(locale, "Découvrir l’intendance", "Explore second-home care")}${arrow}</a></div><a class="partners-team-link" href="${path(locale, "about")}">${t(locale, "Faire connaissance avec Inastia", "Get to know Inastia")} ${arrow}</a></div></div></section>

    <section class="partners-section container partners-start" aria-labelledby="partners-start-title"><div class="partners-section-heading"><div><p class="eyebrow">${t(locale, "03 / LE PREMIER PAS", "03 / THE FIRST STEP")}</p><h2 id="partners-start-title">${t(locale, "Du premier message<br><em>à une collaboration.</em>", "From a first message<br><em>to working together.</em>")}</h2></div><p>${t(locale, "Une discussion pour examiner les possibilités. Un cadre convenu avant toute intervention ou mise en relation.", "A conversation to explore the possibilities. Agreed terms before any work or introduction.")}</p></div><ol class="partners-steps">${steps.map(([title, text], index) => `<li><span class="partners-step-number">0${index + 1}</span><h3>${escape(title!)}</h3><p>${escape(text!)}</p></li>`).join("")}</ol></section>

    <section class="partners-section container partners-faq" id="questions-partenaires" aria-labelledby="partners-faq-title"><div><p class="eyebrow">${t(locale, "04 / LES CONDITIONS À CONNAÎTRE", "04 / THE TERMS TO UNDERSTAND")}</p><h2 id="partners-faq-title">${t(locale, "Quelques réponses<br><em>avant de nous écrire.</em>", "A few answers<br><em>before you write.</em>")}</h2></div><div class="faq-list">${partnerFaq[locale].map(({ id, question, answer }) => `<details id="${id}"><summary>${escape(question)}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>${escape(answer)}</p></div></details>`).join("")}</div></section>

    <section class="partners-contact" id="devenir-partenaire" aria-labelledby="partners-contact-title"><div class="container partners-contact-grid"><div class="partners-contact-heading"><p class="eyebrow">${t(locale, "05 / FAISONS CONNAISSANCE", "05 / LET’S GET ACQUAINTED")}</p><h2 id="partners-contact-title">${t(locale, "Présentez-nous<br><em>votre activité.</em>", "Tell us about<br><em>your business.</em>")}</h2><p>${t(locale, "Un premier message suffit<br>pour ouvrir la discussion.", "A first message is all it takes<br>to start the conversation.")}</p>${connectionMark}</div><div class="partners-contact-action"><p>${t(locale, "Quelques lignes suffisent pour comprendre ce que vous envisagez.", "A few lines are enough to understand what you have in mind.")}</p><ul class="partners-contact-checklist"><li>${t(locale, "Votre nom et votre structure, le cas échéant", "Your name and business, if applicable")}</li><li>${t(locale, "Votre activité", "Your activity")}</li><li>${t(locale, "Les communes d’intervention ou des projets", "The towns you cover or where the projects are located")}</li><li>${t(locale, "La collaboration envisagée", "The collaboration you have in mind")}</li></ul><a class="button button-cream" data-partner-profile="general" data-contact-placement="contact" href="${partnerMail(locale)}">${t(locale, "Présenter mon activité par email", "Introduce my business by email")}${arrow}</a><p class="partners-mail-help">${t(locale, "Un message à compléter dans votre messagerie. Vous l’envoyez après relecture. L’ouverture du message ne transmet pas votre demande à Inastia.", "Complete the draft in your email app and send it after reviewing it. Opening the draft does not send your enquiry to Inastia.")}</p><div class="partners-direct"><p>${t(locale, "Rien ne s’ouvre ? Écrivez directement à", "Nothing opens? Email us directly at")}<a data-partner-profile="general" data-contact-placement="email_fallback" href="mailto:contact@inastia.fr">contact@inastia.fr</a></p><p>${t(locale, "Vous préférez appeler ?", "Prefer to call?")}<a data-partner-profile="general" data-contact-placement="phone" href="tel:+33613812550">+33 6 13 81 25 50</a></p></div><p class="partners-contact-note">${t(locale, "Pour ce premier contact, vos informations professionnelles suffisent. Ne transmettez pas les coordonnées d’un propriétaire ; son accord sera nécessaire avant toute transmission ultérieure.", "Your own professional details are enough for this first contact. Please do not share a homeowner’s contact details; their permission will be needed before any later introduction.")}</p></div></div></section>
  </div>`;
}
