import type { Locale } from "./content/pages.ts";
import { privateConciergeMail, privateFaq, privateServices } from "./content/private-concierge.ts";
import { arrow, escape, path, t } from "./lib.ts";

function photo(name: string, alt: string, priority = false): string {
  return `<picture><source type="image/avif" srcset="/images/${name}-480.avif 480w, /images/${name}-800.avif 800w, /images/${name}-1200.avif 1200w" sizes="(min-width: 900px) 55vw, 100vw"><img src="/images/${name}-800.webp" srcset="/images/${name}-480.webp 480w, /images/${name}-800.webp 800w, /images/${name}-1200.webp 1200w" sizes="(min-width: 900px) 55vw, 100vw" width="1200" height="805" alt="${escape(alt)}" ${priority ? 'fetchpriority="high" loading="eager"' : 'loading="lazy"'} decoding="async"></picture>`;
}

export function privateConcierge(locale: Locale): string {
  return `<div class="private-page">
    <section class="private-hero" aria-labelledby="private-title">
      <div class="private-hero-copy"><nav class="breadcrumb" aria-label="${t(locale, "Fil d’Ariane", "Breadcrumb")}"><a href="${path(locale)}">${t(locale, "Accueil", "Home")}</a><span aria-hidden="true">/</span><span>${t(locale, "Conciergerie privée", "Private concierge")}</span></nav>
        <p class="eyebrow">${t(locale, "CONCIERGERIE PRIVÉE EN CORSE · SAISON 2027", "PRIVATE CONCIERGE IN CORSICA · SEASON 2027")}</p>
        <h1 id="private-title">${t(locale, "Votre temps.<br><em>La Corse.<br>Et vos envies.</em>", "Your time.<br><em>Corsica.<br>Your way.</em>")}</h1>
        <p class="private-lead">${t(locale, "Retrouver votre maison. Partager un dîner. Prendre le large. Préparons les détails qui feront du bien à votre séjour.", "Come home to Corsica. Share a dinner. Head out to sea. Let’s plan the details that will make your stay feel special.")}</p>
        <a class="button" href="#votre-projet">${t(locale, "Préparer mon séjour 2027", "Plan my 2027 stay")}${arrow}</a>
        <p class="private-season">${t(locale, "Notre offre se prépare pour 2027. Présentez-nous déjà votre projet ; prestations et disponibilités seront confirmées dans votre proposition.", "Our service is taking shape for 2027. Share your plans now; services and availability will be confirmed in your proposal.")}</p>
      </div>
      <figure class="private-hero-photo">${photo("villa_lova", t(locale, "Cala Lova, une maison du portfolio Inastia à Cala d’Oro, Solenzara", "Cala Lova, a home in the Inastia portfolio in Cala d’Oro, Solenzara"), true)}<figcaption>Cala Lova <span>Cala d’Oro · Solenzara</span></figcaption><span class="private-photo-note">${t(locale, "L’hospitalité, à votre rythme.", "Hospitality, at your own pace.")}</span></figure>
    </section>

    <nav class="private-contents container" aria-label="${t(locale, "Explorer la conciergerie privée", "Explore private concierge services")}"><a href="#proprietaires">01 ${t(locale, "Votre maison", "Your home")}${arrow}</a><a href="#voyageurs">02 ${t(locale, "Votre séjour", "Your stay")}${arrow}</a><a href="#vos-envies">03 ${t(locale, "Vos envies", "Your preferences")}${arrow}</a></nav>

    <section class="private-intro container"><p class="eyebrow">${t(locale, "DEUX ACCOMPAGNEMENTS, UNE MÊME ATTENTION", "TWO SERVICES, THE SAME PERSONAL CARE")}</p><h2>${t(locale, "Vous avez une maison ici.<br><em>Ou simplement envie d’y être.</em>", "You have a home here.<br><em>Or simply wish you were here.</em>")}</h2><p>${t(locale, "Propriétaires et voyageurs n’ont pas les mêmes besoins. Nous préparons deux façons de vous accompagner, avec un interlocuteur pour faire le point sur vos priorités et une proposition qui précise chaque prestation.", "Homeowners and guests have different needs. We are preparing two ways to support you, with a point of contact to discuss your priorities and a proposal that sets out every service.")}</p></section>

    <section class="private-owner container" id="proprietaires" aria-labelledby="owner-title"><figure>${photo("villa_amichi", t(locale, "Terrasse et piscine de la Villa d’Amichi, à Pinarello, Zonza", "Terrace and pool at Villa d’Amichi in Pinarello, Zonza"))}<figcaption>Villa d’Amichi · Pinarello · Zonza</figcaption></figure><div class="private-offer-copy"><p class="eyebrow">${t(locale, "01 / POUR LES PROPRIÉTAIRES", "01 / FOR HOMEOWNERS")}</p><h2 id="owner-title">${t(locale, "Maison privée.<br><em>Le plaisir de revenir.</em>", "Your private home.<br><em>The joy of returning.</em>")}</h2><p>${t(locale, "Pour vos séjours personnels, vos week-ends et les proches que vous recevez : préparons la maison et les services dont vous souhaitez profiter sur place.", "For your own visits, weekends and the people you welcome: let’s prepare your home and the services you would like while you are here.")}</p><ul><li>${t(locale, "Préparation avant votre arrivée et fermeture après votre départ.", "Preparation before you arrive and closing up after you leave.")}</li><li>${t(locale, "Organisation du ménage, du linge et des achats convenus.", "Arrangements for cleaning, linen and agreed purchases.")}</li><li>${t(locale, "Coordination des rendez-vous et des attentions pour vos proches.", "Coordination of appointments and thoughtful touches for your guests.")}</li></ul><a class="text-link" href="${privateConciergeMail(locale, true)}">${t(locale, "Parlons de mes séjours", "Let’s discuss my visits")}${arrow}</a><p class="private-related">${t(locale, "Pendant vos absences, découvrez aussi", "While you are away, explore")} <a href="${path(locale, "intendance-residence-secondaire-corse")}">${t(locale, "l’intendance de résidence secondaire", "our second-home care")}</a>.</p></div></section>

    <section class="private-guest" id="voyageurs" aria-labelledby="guest-title"><div class="container private-guest-grid"><div><p class="eyebrow">${t(locale, "02 / POUR LES VOYAGEURS", "02 / FOR GUESTS")}</p><h2 id="guest-title">${t(locale, "Séjour privé.<br><em>La place aux vacances.</em>", "Your private stay.<br><em>Make room for holidays.</em>")}</h2><a class="button button-cream" href="${privateConciergeMail(locale, false)}">${t(locale, "Partageons mes envies", "Share my preferences")}${arrow}</a></div><div><p class="private-guest-lead">${t(locale, "Une semaine en famille, quelques jours à deux ou des vacances entre amis. Dites-nous ce qui compte pour vous ; nous étudierons les services adaptés à votre séjour.", "A week with family, a few days as a couple or a holiday with friends. Tell us what matters to you; we will explore services suited to your stay.")}</p><ul><li>${t(locale, "Une arrivée plus simple et les besoins pratiques anticipés.", "An easier arrival, with practical needs considered in advance.")}</li><li>${t(locale, "Des repas, des moments de détente et des sorties à envisager.", "Meals, relaxing moments and outings to plan.")}</li><li>${t(locale, "Un programme construit autour de vos dates et de votre budget.", "Arrangements shaped around your dates and budget.")}</li></ul><p class="private-guest-note">${t(locale, "Vous pourrez nous présenter un projet même dans un logement qui n’est pas géré par Inastia. Nous en vérifierons la faisabilité avec vous.", "You may share your plans even if Inastia does not manage your accommodation. We will check what is possible with you.")}</p></div></div></section>

    <section class="private-services container" id="vos-envies" aria-labelledby="services-title"><div class="private-section-heading"><p class="eyebrow">${t(locale, "LE CARNET DES ENVIES · 2027", "YOUR HOLIDAY WISH LIST · 2027")}</p><h2 id="services-title">${t(locale, "De petites attentions.<br><em>De beaux moments.</em>", "Thoughtful touches.<br><em>Memorable moments.</em>")}</h2><p>${t(locale, "Voici les services que nous préparons pour la prochaine saison. Leur organisation sera étudiée selon votre demande et les professionnels disponibles.", "These are the services we are preparing for next season. Arrangements will be assessed according to your request and the professionals available.")}</p></div><div class="private-services-grid">${privateServices[locale].map((service, index) => `<article><span class="private-number" aria-hidden="true">0${index + 1}</span><h3>${escape(service.title)}</h3><p>${escape(service.text)}</p></article>`).join("")}</div></section>

    <section class="private-process container" aria-labelledby="process-title"><div><p class="eyebrow">${t(locale, "UN CADRE CLAIR, DÈS LE DÉPART", "CLEAR ARRANGEMENTS FROM THE START")}</p><h2 id="process-title">${t(locale, "Vos envies.<br><em>Une proposition précise.</em>", "Your preferences.<br><em>A detailed proposal.</em>")}</h2></div><ol><li><h3>${t(locale, "Vous nous racontez.", "Tell us your plans.")}</h3><p>${t(locale, "Les dates, la commune, le nombre de personnes et les services souhaités. Même si tout n’est pas encore décidé.", "Your dates, location, number of guests and the services you have in mind. It is fine if some details are still undecided.")}</p></li><li><h3>${t(locale, "Nous étudions les possibilités.", "We explore the possibilities.")}</h3><p>${t(locale, "Nous vérifions le secteur, les accès et les disponibilités avant de vous présenter une proposition personnalisée.", "We check the area, property access and availability before presenting a personalised proposal.")}</p></li><li><h3>${t(locale, "Vous choisissez, en connaissance de cause.", "You choose with the details in hand.")}</h3><p>${t(locale, "Honoraires d’organisation, déplacements éventuels, achats et prestations extérieures sont identifiés séparément. Vous validez le contenu et les conditions avant tout engagement.", "Organisation fees, any travel costs, purchases and external services are identified separately. You approve the scope and terms before making a commitment.")}</p></li></ol></section>

    <section class="private-faq container" id="faq" aria-labelledby="private-faq-title"><h2 id="private-faq-title">${t(locale, "Avant de préparer<br><em>votre prochaine saison.</em>", "Before planning<br><em>your next season.</em>")}</h2><div class="faq-list">${privateFaq[locale].map(item => `<details><summary>${escape(item.question)}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>${escape(item.answer)}</p></div></details>`).join("")}</div></section>

    <section class="private-final" id="votre-projet" aria-labelledby="private-final-title"><div class="container"><p class="eyebrow">${t(locale, "GHISONACCIA · SOLENZARA · PORTO-VECCHIO", "GHISONACCIA · SOLENZARA · PORTO-VECCHIO")}</p><h2 id="private-final-title">${t(locale, "L’été prochain<br><em>commence par vos envies.</em>", "Next summer<br><em>starts with your plans.</em>")}</h2><p>${t(locale, "Présentez-nous votre projet pour 2027. Ce premier échange nous permettra de préparer un accompagnement à votre mesure.", "Tell us about your plans for 2027. This first conversation will help us prepare support around your needs.")}</p><div class="private-actions"><a class="button" href="${privateConciergeMail(locale, true)}">${t(locale, "Je suis propriétaire", "I am a homeowner")}${arrow}</a><a class="button button-outline" href="${privateConciergeMail(locale, false)}">${t(locale, "Je prépare des vacances", "I am planning a holiday")}${arrow}</a></div><p class="private-mail-note">${t(locale, "Ces liens ouvrent votre messagerie avec un message à compléter.", "These links open your email app with a message for you to complete.")}</p><p class="private-direct"><a href="mailto:contact@inastia.fr">contact@inastia.fr</a><a href="tel:+33613812550">+33 6 13 81 25 50</a></p><p class="private-final-note">${t(locale, "Offre en préparation pour 2027. Votre demande n’est pas une réservation ; services, tarifs et disponibilités seront confirmés avant votre accord.", "Service in preparation for 2027. Your enquiry is not a booking; services, prices and availability will be confirmed before your approval.")}</p></div></section>
  </div>`;
}
