import type { Locale } from "./content/pages.ts";
import { privateConciergeMail, privateFaq, privateServices } from "./content/private-concierge.ts";
import { arrow, escape, path, t } from "./lib.ts";

function photo(name: string, alt: string, priority = false): string {
  return `<picture><source type="image/avif" srcset="/images/${name}-480.avif 480w, /images/${name}-800.avif 800w, /images/${name}-1200.avif 1200w" sizes="(min-width: 900px) 55vw, 100vw"><img src="/images/${name}-800.webp" srcset="/images/${name}-480.webp 480w, /images/${name}-800.webp 800w, /images/${name}-1200.webp 1200w" sizes="(min-width: 900px) 55vw, 100vw" width="1200" height="805" alt="${escape(alt)}" ${priority ? 'fetchpriority="high" loading="eager"' : 'loading="lazy"'} decoding="async"></picture>`;
}

export function privateConcierge(locale: Locale): string {
  return `<div class="private-page">
    <section class="private-hero" aria-labelledby="private-title">
      <div class="private-hero-copy"><nav class="breadcrumb" aria-label="${t(locale, "Fil d’Ariane", "Breadcrumb")}"><a href="${path(locale)}">${t(locale, "Accueil", "Home")}</a><span aria-hidden="true">/</span><span>${t(locale, "Conciergerie privée", "Private concierge")}</span></nav>
        <p class="eyebrow">${t(locale, "CONCIERGERIE PRIVÉE EN CORSE · SAISON 2027", "PRIVATE CONCIERGE IN CORSICA · SEASON 2027")}</p>
        <h1 id="private-title">${t(locale, "Vos vacances.<br><em>Les services<br>qui vont avec.</em>", "Your holiday.<br><em>The services<br>to go with it.</em>")}</h1>
        <p class="private-lead">${t(locale, "Un chef à la maison, une journée en bateau, un massage ou les courses livrées à votre arrivée. Choisissez les prestations qui feront partie de votre séjour en Corse.", "A chef at home, a day on a boat, a massage or groceries delivered for your arrival. Choose the services you would like during your stay in Corsica.")}</p>
        <a class="button" href="#prestations">${t(locale, "Découvrir les prestations", "Explore the services")}${arrow}</a>
        <p class="private-season">${t(locale, "Catalogue en préparation pour 2027. Vous pouvez déjà nous présenter vos envies ; chaque prestation sera confirmée sur devis, selon les professionnels et les disponibilités.", "Our catalogue is being prepared for 2027. Share your wishes now; each service will be confirmed in a quote, subject to providers and availability.")}</p>
      </div>
      <figure class="private-hero-photo">${photo("villa_lova", t(locale, "Cala Lova, une maison du portfolio Inastia à Cala d’Oro, Solenzara", "Cala Lova, a home in the Inastia portfolio in Cala d’Oro, Solenzara"), true)}<figcaption>Cala Lova <span>Cala d’Oro · Solenzara</span></figcaption><span class="private-photo-note">${t(locale, "Les vacances se savourent.", "Holidays to savour.")}</span></figure>
    </section>

    <nav class="private-contents container" aria-label="${t(locale, "Explorer la conciergerie privée", "Explore private concierge services")}"><a href="#prestations">01 ${t(locale, "Les prestations", "The services")}${arrow}</a><a href="#vos-sejours">02 ${t(locale, "Pour vos séjours", "For your stays")}${arrow}</a><a href="#sur-mesure">03 ${t(locale, "Sur mesure", "Your way")}${arrow}</a></nav>

    <section class="private-services container" id="prestations" aria-labelledby="services-title"><div class="private-section-heading"><p class="eyebrow">${t(locale, "LE CATALOGUE · 2027", "THE CATALOGUE · 2027")}</p><h2 id="services-title">${t(locale, "De quoi avez-vous envie ?<br><em>Commençons par là.</em>", "What would you enjoy?<br><em>Let’s start there.</em>")}</h2><p>${t(locale, "Une seule prestation ou plusieurs services pendant vos vacances : présentez-nous votre demande. Nous en étudierons les détails, les possibilités et le prix avec les professionnels concernés.", "One service or several throughout your holiday: tell us what you have in mind. We will explore the details, availability and price with the relevant professionals.")}</p></div><div class="private-services-grid">${privateServices[locale].map((service, index) => `<article><span class="private-number" aria-hidden="true">${String(index + 1).padStart(2, "0")}</span><h3>${escape(service.title)}</h3><p>${escape(service.text)}</p><p class="private-service-details">${escape(service.details)}</p><a class="text-link" href="${privateConciergeMail(locale, null, service.title)}" aria-label="${escape(t(locale, `Demander un devis : ${service.title}`, `Request a quote: ${service.title}`))}">${t(locale, "Demander un devis", "Request a quote")}${arrow}</a></article>`).join("")}</div><p class="private-catalogue-note">${t(locale, "Les liens ouvrent votre messagerie avec la prestation choisie. Votre demande pour 2027 ne constitue pas une réservation.", "The links open your email app with your chosen service. Your enquiry for 2027 is not a booking.")}</p></section>

    <section class="private-guest" id="vos-sejours" aria-labelledby="audience-title"><div class="container"><p class="eyebrow">${t(locale, "PROPRIÉTAIRES & VOYAGEURS", "HOMEOWNERS & GUESTS")}</p><h2 id="audience-title">${t(locale, "Votre maison ou vos vacances.<br><em>Les mêmes envies de profiter.</em>", "Your home or your holiday.<br><em>More time to enjoy it.</em>")}</h2><div class="private-guest-grid"><article id="proprietaires"><h3>${t(locale, "Vous êtes propriétaire", "You are a homeowner")}</h3><p>${t(locale, "Pour vos séjours personnels et les proches que vous recevez : un chef pour le dîner, du linge, des courses, une garde d’enfants ou une occasion à célébrer chez vous.", "For your own visits and the people you welcome: a chef for dinner, linen, groceries, childcare or an occasion to celebrate at home.")}</p><a class="text-link" href="${privateConciergeMail(locale, true)}">${t(locale, "Préparer mes séjours à la maison", "Plan my visits at home")}${arrow}</a></article><article id="voyageurs"><h3>${t(locale, "Vous êtes voyageur", "You are a guest")}</h3><p>${t(locale, "Pour vos vacances en Corse : une arrivée facilitée, des services dans votre location et des moments à partager. Vous pouvez nous contacter même si votre logement n’est pas géré par Inastia.", "For your holiday in Corsica: an easier arrival, services at your rental and moments to share. You can contact us even if Inastia does not manage your accommodation.")}</p><a class="text-link" href="${privateConciergeMail(locale, false)}">${t(locale, "Préparer les services de mes vacances", "Plan my holiday services")}${arrow}</a></article></div><p class="private-guest-note">${t(locale, "Les prestations déjà incluses dans votre contrat restent prises en compte. Pour le suivi de votre maison pendant vos absences, découvrez", "Services already included in your contract are taken into account. For looking after your home while you are away, explore")} <a href="${path(locale, "intendance-residence-secondaire-corse")}">${t(locale, "l’intendance de résidence secondaire", "our second-home care")}</a>.</p></div></section>

    <section class="private-formulas container" id="sur-mesure" aria-labelledby="formulas-title"><div class="private-section-heading"><p class="eyebrow">${t(locale, "À VOTRE MESURE", "AROUND YOUR NEEDS")}</p><h2 id="formulas-title">${t(locale, "Une envie précise.<br><em>Ou tout un séjour à imaginer.</em>", "One particular wish.<br><em>Or a whole stay to plan.</em>")}</h2></div><div class="private-formulas-grid"><article><h3>${t(locale, "À la carte", "À la carte")}</h3><p>${t(locale, "Un chef, une livraison, un massage, un bateau… Une demande ciblée et une proposition pour la prestation choisie.", "A chef, a delivery, a massage, a boat… A specific request and a proposal for your chosen service.")}</p><span>${t(locale, "Sur devis", "By quotation")}</span></article><article><h3>${t(locale, "Pour votre séjour", "For your stay")}</h3><p>${t(locale, "Plusieurs envies à organiser autour des mêmes dates. Une proposition d’ensemble qui détaille les services, leur calendrier et leur coût.", "Several wishes to arrange around the same dates. An overall proposal detailing the services, their schedule and cost.")}</p><span>${t(locale, "Sur devis personnalisé", "Personalised quotation")}</span></article><article><h3>${t(locale, "Pour un événement", "For an event")}</h3><p>${t(locale, "Un anniversaire ou un repas privé. Un projet défini selon le lieu, les invités et les intervenants nécessaires.", "A birthday or private meal. A project defined around the venue, guests and professionals needed.")}</p><span>${t(locale, "Sur devis événementiel", "Event quotation")}</span></article></div></section>

    <section class="private-process container" aria-labelledby="process-title"><div><p class="eyebrow">${t(locale, "COMMENT ÇA SE PASSE", "HOW IT WORKS")}</p><h2 id="process-title">${t(locale, "Vous choisissez.<br><em>Nous préparons la suite.</em>", "You choose.<br><em>We plan the next steps.</em>")}</h2></div><ol><li><h3>${t(locale, "Racontez-nous votre envie.", "Tell us what you have in mind.")}</h3><p>${t(locale, "Choisissez une prestation et indiquez vos dates, votre commune, le nombre de personnes et votre budget indicatif.", "Choose a service and share your dates, location, number of guests and indicative budget.")}</p></li><li><h3>${t(locale, "Recevez une proposition précise.", "Receive a detailed proposal.")}</h3><p>${t(locale, "Nous étudions la faisabilité et les disponibilités. Le devis précise le service, son prix, les frais éventuels et les conditions de règlement et d’annulation.", "We assess feasibility and availability. Your quote sets out the service, its price, any fees, and payment and cancellation terms.")}</p></li><li><h3>${t(locale, "Validez les détails de votre séjour.", "Confirm the details of your stay.")}</h3><p>${t(locale, "Les prestations retenues, les professionnels concernés et les créneaux sont confirmés avant leur réalisation. Vous savez ce qui est prévu et qui contacter.", "Your chosen services, the professionals involved and appointments are confirmed before delivery. You know what is planned and whom to contact.")}</p></li></ol></section>

    <section class="private-faq container" id="faq" aria-labelledby="private-faq-title"><h2 id="private-faq-title">${t(locale, "Avant de choisir<br><em>vos prestations.</em>", "Before choosing<br><em>your services.</em>")}</h2><div class="faq-list">${privateFaq[locale].map(item => `<details><summary>${escape(item.question)}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>${escape(item.answer)}</p></div></details>`).join("")}</div></section>

    <section class="private-final" id="votre-projet" aria-labelledby="private-final-title"><div class="container"><p class="eyebrow">GHISONACCIA · SOLENZARA · PORTO-VECCHIO</p><h2 id="private-final-title">${t(locale, "Qu’aimeriez-vous prévoir<br><em>pour vos prochaines vacances ?</em>", "What would you like<br><em>for your next holiday?</em>")}</h2><p>${t(locale, "Partagez vos dates et vos envies pour 2027. Une prestation ou plusieurs : votre demande sera étudiée selon le lieu, le budget et les possibilités.", "Share your dates and preferences for 2027. One service or several: we will assess your request according to the location, budget and available options.")}</p><div class="private-actions"><a class="button" href="${privateConciergeMail(locale, true)}">${t(locale, "Je suis propriétaire", "I am a homeowner")}${arrow}</a><a class="button" href="${privateConciergeMail(locale, false)}">${t(locale, "Je prépare des vacances", "I am planning a holiday")}${arrow}</a></div><p class="private-mail-note">${t(locale, "Ces liens ouvrent votre messagerie avec un message à compléter.", "These links open your email app with a message to complete.")}</p><div class="private-direct"><a href="mailto:contact@inastia.fr">contact@inastia.fr</a><a href="tel:+33618182550">+33 6 18 18 25 50</a></div><p class="private-final-note">${t(locale, "Prestations en préparation pour 2027, sur devis et selon disponibilités. Une demande ne vaut pas confirmation de réservation.", "Services in preparation for 2027, by quotation and subject to availability. An enquiry does not confirm a booking.")}</p></div></section>
  </div>`;
}
